"""
Build a YOLO detection dataset from MinneApple detection/train (instance masks -> bbox labels).
Output: yolo/images/{train,val}, yolo/labels/{train,val}, yolo/data.yaml
Requires: pip install pillow numpy
"""

from __future__ import annotations

import os
import random
import shutil
from pathlib import Path

import numpy as np
from PIL import Image

ROOT = Path(__file__).resolve().parent
DET_TRAIN = ROOT / "detection" / "train"
IM_DIR = DET_TRAIN / "images"
MASK_DIR = DET_TRAIN / "masks"
OUT = ROOT / "yolo"
VAL_RATIO = 0.15
SEED = 42


def mask_to_yolo_lines(mask_arr: np.ndarray) -> list[str]:
    h, w = mask_arr.shape[:2]
    if mask_arr.ndim == 3:
        raise ValueError("Expected single-channel mask PNG")
    obj_ids = np.unique(mask_arr)
    obj_ids = obj_ids[obj_ids != 0]
    lines: list[str] = []
    for oid in obj_ids:
        m = mask_arr == oid
        ys, xs = np.where(m)
        if ys.size == 0:
            continue
        xmin, xmax = int(xs.min()), int(xs.max())
        ymin, ymax = int(ys.min()), int(ys.max())
        if xmin >= xmax or ymin >= ymax:
            continue
        xmin = max(0, min(xmin, w - 1))
        xmax = max(0, min(xmax, w - 1))
        ymin = max(0, min(ymin, h - 1))
        ymax = max(0, min(ymax, h - 1))
        bw, bh = xmax - xmin, ymax - ymin
        cx = (xmin + xmax) / 2.0 / w
        cy = (ymin + ymax) / 2.0 / h
        nw = bw / w
        nh = bh / h
        lines.append(f"0 {cx:.6f} {cy:.6f} {nw:.6f} {nh:.6f}")
    return lines


def main() -> None:
    if not IM_DIR.is_dir() or not MASK_DIR.is_dir():
        raise SystemExit(
            f"Missing {IM_DIR} or {MASK_DIR}. Extract detection.tar.gz first."
        )

    imgs = sorted(os.listdir(IM_DIR))
    assert imgs == sorted(os.listdir(MASK_DIR)), "images/masks filename mismatch"

    random.seed(SEED)
    idx = list(range(len(imgs)))
    random.shuffle(idx)
    n_val = max(1, int(len(imgs) * VAL_RATIO))
    val_set = set(idx[:n_val])

    for d in (OUT / "images" / "train", OUT / "images" / "val", OUT / "labels" / "train", OUT / "labels" / "val"):
        d.mkdir(parents=True, exist_ok=True)

    for i, name in enumerate(imgs):
        split = "val" if i in val_set else "train"
        im_path = IM_DIR / name
        mask_path = MASK_DIR / name
        mask = np.array(Image.open(mask_path))
        lines = mask_to_yolo_lines(mask)

        shutil.copy2(im_path, OUT / "images" / split / name)
        label_name = Path(name).stem + ".txt"
        (OUT / "labels" / split / label_name).write_text("\n".join(lines) + ("\n" if lines else ""), encoding="utf-8")

    yaml = f"""# MinneApple -> YOLO (single class apple). Generated by convert_to_yolo.py
path: {OUT.as_posix()}
train: images/train
val: images/val
names:
  0: apple
"""
    (OUT / "data.yaml").write_text(yaml, encoding="utf-8")
    print(f"Done. images: {len(imgs)}, val: {n_val}, train: {len(imgs)-n_val}")
    print(f"data.yaml: {OUT / 'data.yaml'}")
    print("Ultralytics 示例: yolo detect train data=r\"{}\" model=yolo11n.pt epochs=100".format(OUT / "data.yaml"))


if __name__ == "__main__":
    main()
